# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-chatbot

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless-chatbot
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:DetectFaces
      Resource: '*'
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.uploadBucket}/*
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.transformBucket}/*
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:*:*:table/${self:service}-${self:provider.stage}-teams
custom:
  uploadBucket: ${self:service}-${self:provider.stage}-uploads-your-initials-here
  transformBucket: ${self:service}-${self:provider.stage}-transformed-your-initials-here
functions:
  install:
    handler: install.endpoint
    events:
      - http:
          path: install
          method: get
    environment:
      CLIENT_ID: '159801495122.160508499655'
      CLIENT_SECRET: b3f939ef9af2a6c5cc848001f6bac147
      SLACK_OAUTH: 'https://slack.com/api/oauth.access?'
      TABLE_NAME: ${self:service}-${self:provider.stage}-teams
  hello:
    handler: handler.endpoint
    events:
      - http:
          path: echo
          method: post
    environment:
      POST_MESSAGE_URL: 'https://slack.com/api/chat.postMessage?'
      UPLOAD_BUCKET: ${self:custom.uploadBucket}
      SLACK_HOSTNAME: 'files.slack.com'
      TEMP_FOLDER: '/tmp/'
      TEAMS_TABLE: ${self:service}-${self:provider.stage}-teams
  faceswap:
    handler: faceswap.execute
    environment:
      TEMP_FOLDER: '/tmp/'
      OUTPUT_PREFIX: 'output-'
      UPLOAD_BUCKET: ${self:custom.uploadBucket}
      TRANSFORM_BUCKET: ${self:custom.transformBucket}
    events:
      - s3:
          bucket: ${self:custom.uploadBucket}
          event: s3:ObjectCreated:*
  slackupdate:
    handler: slackupdate.execute
    environment:
      POST_MESSAGE_URL: 'https://slack.com/api/chat.postMessage?'
      BOT_ACCESS_TOKEN: 'xoxb-159279836768-FOst5DLfEzmQgkz7cte5qiIv'
      CHANNEL_ID: 'C4QE6KLFQ'
      SHORTENER_API_KEY: 'AIzaSyDO-Y0w0hllv097NGrSUrDoy4Un35jLoSA'
      SHORTENER_API_URL: 'https://www.googleapis.com/urlshortener/v1/url?'
    events:
      - s3:
          bucket: ${self:custom.transformBucket}
          event: s3:ObjectCreated:*
resources:
  Resources:
    TeamsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:service}-${self:provider.stage}-teams
        AttributeDefinitions: 
          - AttributeName: team_id
            AttributeType: S
        KeySchema:
          - AttributeName: team_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1