service: serverless-chatbot

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless-chatbot

functions:
  bot:
    handler: bot.endpoint
  hello:
    handler: handler.endpoint
    events:
      - http:
          path: echo
          method: post
    environment:
      POST_MESSAGE_URL: 'https://slack.com/api/chat.postMessage?'
      BOT_ACCESS_TOKEN: 'ReplaceThisWithYourBotUserOAuthAccessToken'
      BOT_ID: 'ReplaceThisWithTheIdFromYourCommandLineRunOfTheBotFunction'
      VERIFICATION_TOKEN: 'ReplaceThisWithYourVerificationTokenFromBasicInfoInSlackAppsConfig'
